[theme]
primaryColor="#0065BD"            # CSUSB Blue
textColor="#000000"               # Black
backgroundColor="#FFFFFF"         # White base
secondaryBackgroundColor="#F5F7F9" # CSUSB Gray

[server]
enableCORS = false
enableXsrfProtection = true
